export type ChatSuggestion = { id: string; label: string; value: string; variant?: "default" | "warning" | "neutral" };
export type ChatStep = { id: string; section: string; question: string; suggestions: ChatSuggestion[]; type?: "choice" | "text" | "number" | "yesno"; multi?: boolean };

export const gastroSteps: Record<string, ChatStep[]> = {
  general: [
    { id: "general_duration", section: "Additional concern", question: "How long have you been experiencing this concern?", type: "text", suggestions: [] },
    { id: "general_details", section: "Additional concern", question: "Is there anything else you would like Dr. Arif’s team to know?", type: "text", suggestions: [] },
  ],
  abdominal_pain: [
    { id: "pain_location", section: "Abdominal pain", question: "Where is the pain?", suggestions: ["upper abdomen", "lower abdomen", "right upper abdomen", "right lower abdomen", "left upper abdomen", "left lower abdomen", "around the navel", "all over the abdomen", "I’m not sure"].map((x,i) => ({ id: `pain-location-${i}`, label: x[0].toUpperCase()+x.slice(1), value: x })) },
    { id: "pain_severity", section: "Abdominal pain", question: "How severe is the pain?", type: "number", suggestions: ["Mild, 1–3", "Moderate, 4–6", "Severe, 7–8", "Unbearable, 9–10"].map((x,i) => ({ id: `pain-severity-${i}`, label: x, value: x, variant: i > 1 ? "warning" : "default" })) },
    { id: "pain_quality", section: "Abdominal pain", question: "What does the pain feel like?", suggestions: ["Burning", "Cramping", "Sharp", "Stabbing", "Dull ache", "Pressure or heaviness", "Colicky or comes in waves", "I’m not sure"].map((x,i) => ({ id: `pain-quality-${i}`, label: x, value: x })) },
    { id: "pain_timing", section: "Abdominal pain", question: "When does it usually happen?", suggestions: ["After eating", "Before eating", "At night", "Constant", "Comes and goes", "During movement", "During passing stool", "No clear pattern"].map((x,i) => ({ id: `pain-timing-${i}`, label: x, value: x })) },
  ],
  acidity: [
    { id: "acidity_features", section: "Acidity or heartburn", question: "Which symptoms are you noticing?", multi: true, suggestions: ["Burning in chest", "Sour taste in mouth", "Food coming back up", "Worse after meals", "Worse when lying down", "Night-time symptoms", "Difficulty swallowing", "Frequent burping", "Bloating"].map((x,i) => ({ id: `acidity-${i}`, label: x, value: x })) },
    { id: "acidity_duration", section: "Acidity or heartburn", question: "How long has this been happening?", type: "text", suggestions: ["Since today", "2–3 days", "1–4 weeks", "1–3 months", "More than 3 months"].map((x,i) => ({ id: `duration-${i}`, label: x, value: x })) },
  ],
  vomiting: [{ id: "vomiting_features", section: "Vomiting or nausea", question: "What best describes the problem?", multi: true, suggestions: ["Nausea only", "Vomiting once", "Vomiting several times", "Vomiting after food", "Unable to keep fluids down", "Blood in vomit", "Greenish vomiting", "Coffee-ground-like vomiting"].map((x,i) => ({ id: `vomiting-${i}`, label: x, value: x, variant: /blood|coffee|fluids/i.test(x) ? "warning" : "default" })) }],
  bowel: [{ id: "bowel_features", section: "Bowel symptoms", question: "Which bowel changes are you noticing?", multi: true, suggestions: ["Hard stool", "Passing stool less often", "Straining", "Loose stool", "Watery stool", "Blood in stool", "Mucus in stool", "Abdominal cramps", "Recent antibiotics", "Recent travel"].map((x,i) => ({ id: `bowel-${i}`, label: x, value: x, variant: /blood/i.test(x) ? "warning" : "default" })) }],
  cancer: [{ id: "cancer_context", section: "Cancer-related consultation", question: "What would you like Dr. Arif to review?", suggestions: ["Newly diagnosed cancer", "Suspected cancer", "Biopsy report available", "Scan report available", "Seeking surgical opinion", "Follow-up after cancer treatment", "Chemotherapy completed", "Radiotherapy completed", "Recurrence concern"].map((x,i) => ({ id: `cancer-${i}`, label: x, value: x })) }],
  difficulty_swallowing: [{ id: "swallowing_features", section: "Difficulty swallowing", question: "What best describes the swallowing problem?", multi: true, suggestions: ["Difficulty with solid food", "Difficulty with liquids", "Difficulty with both", "Food feels stuck", "Pain while swallowing", "Coughing while swallowing", "Symptoms getting worse", "Associated weight loss"].map((x,i) => ({ id: `swallowing-${i}`, label: x, value: x, variant: /worse|weight/i.test(x) ? "warning" : "default" })) }],
  jaundice: [{ id: "jaundice_features", section: "Yellow eyes or jaundice", question: "Which symptoms are present?", multi: true, suggestions: ["Yellow eyes", "Yellow skin", "Dark urine", "Pale stool", "Itching", "Fever", "Right upper abdominal pain", "Loss of appetite", "Weight loss", "Confusion or unusual drowsiness"].map((x,i) => ({ id: `jaundice-${i}`, label: x, value: x, variant: /confusion|fever/i.test(x) ? "warning" : "default" })) }],
  swelling: [{ id: "swelling_features", section: "Abdominal swelling or hernia", question: "What best describes the swelling?", multi: true, suggestions: ["General abdominal swelling", "Localised lump", "Swelling increases on coughing", "Swelling reduces when lying down", "Painful swelling", "Sudden swelling", "Swelling with vomiting", "Unable to pass stool or gas", "Swelling cannot be pushed back"].map((x,i) => ({ id: `swelling-${i}`, label: x, value: x, variant: /painful|vomiting|cannot|unable/i.test(x) ? "warning" : "default" })) }],
  gallbladder: [{ id: "gallbladder_features", section: "Gallbladder-related symptoms", question: "Which symptoms or history apply?", multi: true, suggestions: ["Right upper abdominal pain", "Pain after oily food", "Pain spreading to right shoulder", "Nausea or vomiting", "Fever", "Yellow eyes", "Previously diagnosed gallstones", "Ultrasound available"].map((x,i) => ({ id: `gallbladder-${i}`, label: x, value: x, variant: /fever|yellow/i.test(x) ? "warning" : "default" })) }],
  weight_loss: [{ id: "weight_loss_context", section: "Weight and appetite", question: "Was the weight loss intentional?", suggestions: ["Yes, intentional", "No, unintentional", "Not sure"].map((x,i) => ({ id: `weight-loss-${i}`, label: x, value: x, variant: i === 1 ? "warning" : "default" })) }],
  post_surgery: [{ id: "post_surgery_features", section: "Post-surgery follow-up", question: "What would you like the team to review?", multi: true, suggestions: ["Routine follow-up", "Wound pain", "Wound redness", "Wound discharge", "Fever", "Vomiting", "Abdominal swelling", "Unable to pass stool or gas", "Drain-related concern", "Stitch or dressing concern"].map((x,i) => ({ id: `post-surgery-${i}`, label: x, value: x, variant: /redness|discharge|fever|vomiting|unable/i.test(x) ? "warning" : "default" })) }],
};

export const openingSuggestions: ChatSuggestion[] = ["Abdominal pain", "Acidity or heartburn", "Vomiting or nausea", "Constipation or diarrhoea", "Blood in stool", "Difficulty swallowing", "Yellow eyes or jaundice", "Abdominal swelling or hernia", "Unexplained weight loss", "Cancer-related consultation", "Follow-up after surgery", "I have reports to review", "Something else"].map((x,i) => ({ id: `opening-${i}`, label: x, value: x }));
