"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { getSupabase, isSupabaseConfigured } from "@/lib/supabase";
import { resolveUserRole } from "@/lib/use-user-role";
import { Eye, EyeOff, LockKeyhole } from "@/components/icons";
export default function Login(){
  const [signup,setSignup]=useState(false);const [showPassword,setShowPassword]=useState(false);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const router=useRouter();
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const fd=new FormData(e.currentTarget);const email=String(fd.get("email"));const password=String(fd.get("password"));const supabase=getSupabase();if(!supabase){setMessage("Connect Supabase to enable secure account access.");setBusy(false);return}if(signup){const {error}=await supabase.auth.signUp({email,password,options:{data:{full_name:fd.get("name")}}});setMessage(error?.message||"Check your email to confirm your account.");}else{const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message);else if(data.user){const result=await resolveUserRole(supabase,data.user.id);router.replace(result.role==="admin"?"/admin":"/portal");router.refresh();}}setBusy(false)}
  return <section className="auth-shell"><div className="auth-card"><span className="brand-mark"><LockKeyhole/></span><h1>{signup?"Create patient account":"Welcome back"}</h1><p>{signup?"Keep your appointment requests linked to one secure account.":"Sign in to view your appointment requests and status."}</p><form className="auth-form" onSubmit={submit}>{signup&&<label>Full name<input name="name" required/></label>}<label>Email address<input type="email" name="email" required/></label><label>Password<div className="password-field"><input type={showPassword?"text":"password"} name="password" minLength={8} required/><button type="button" className="password-toggle" onClick={()=>setShowPassword(value=>!value)} aria-label={showPassword?"Hide password":"Show password"} title={showPassword?"Hide password":"Show password"}>{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{message&&<p className="form-error">{message}</p>}<button className="button" disabled={busy}>{busy?"Please wait…":signup?"Create account":"Sign in"}</button></form><p className="auth-toggle">{signup?"Already registered?":"New patient?"} <button className="text-button" onClick={()=>setSignup(!signup)}>{signup?"Sign in":"Create an account"}</button></p>{!isSupabaseConfigured&&<p className="form-note">Demo preview is active. Add Supabase variables to enable login.</p>}</div></section>
}
